name: CI/CD Pipeline

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install --force

      - name: Build Project
        run: npm run build
        
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel login --token=${{ secrets.VERCEL_TOKEN }}
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          
